#!/usr/bin/env bash
# status.sh — regenerate STATUS.md from live repo facts (the anti-drift mechanism).
#
# Computes, live: the Godot engine version (from project.godot config/features),
# the git short commit + branch, the number of headless test methods (func test_
# across tests/*.gd), and the seed-validation result. Everything a stale number
# in a doc would otherwise misreport is derived here instead.
#
# Dependency-free: bash + grep + git + python3. Does NOT run the Godot test suite
# (that needs a binary that may be absent) — it only DISCOVERS the test count and
# tells you to run scripts/run_sim_tests.sh to execute them.
#
# Usage: bash scripts/status.sh   (writes ./STATUS.md; do not hand-edit STATUS.md)
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
OUT="STATUS.md"

# --- Engine version: parse the minor version out of project.godot config/features ---
ENGINE="$(grep -E 'config/features' project.godot 2>/dev/null | grep -oE '[0-9]+\.[0-9]+' | head -1)"
[ -z "$ENGINE" ] && ENGINE="unknown"

# --- Git short commit + branch (guarded for a non-git export) ---
if git rev-parse --git-dir >/dev/null 2>&1; then
	COMMIT="$(git rev-parse --short HEAD)"
	BRANCH="$(git rev-parse --abbrev-ref HEAD)"
else
	COMMIT="(not a git checkout)"
	BRANCH="(unknown)"
fi

# --- Test methods discovered (func test_ declarations across tests/*.gd) ---
TESTS="$(grep -rhE '^[[:space:]]*func[[:space:]]+test_' tests/*.gd 2>/dev/null | wc -l | tr -d ' ')"
[ -z "$TESTS" ] && TESTS=0

# --- Seed validation (run it, capture pass/fail + the summary line) ---
SEED_OUT="$(python3 scripts/validate_seeds.py 2>&1)"
SEED_EXIT=$?
SEED_SUMMARY="$(printf '%s\n' "$SEED_OUT" | tail -1)"
if [ "$SEED_EXIT" -eq 0 ]; then
	SEED_STATUS="PASS (exit 0)"
else
	SEED_STATUS="FAIL (exit $SEED_EXIT)"
fi

GEN="$(date -u '+%Y-%m-%d %H:%M UTC')"

# --- Emit STATUS.md: dynamic header first, then the static prose sections ---
{
	echo "<!-- Generated by scripts/status.sh — do not hand-edit. Regenerate: bash scripts/status.sh -->"
	echo "# Project status — Galactic Prime Time"
	echo
	echo "> **Generated by \`scripts/status.sh\` — do not hand-edit.**"
	echo "> Regenerate with \`bash scripts/status.sh\`. Generated: ${GEN}."
	echo
	echo "## Engine"
	echo "- Godot **${ENGINE}.x** (project targets ${ENGINE} features; \`scripts/setup_godot.sh\` fetches 4.7.1)"
	echo
	echo "## Commit / branch"
	echo "- Commit \`${COMMIT}\` on branch \`${BRANCH}\`"
	echo
	echo "## Tests"
	echo "- Tests discovered: **${TESTS}** (run \`scripts/run_sim_tests.sh\` to execute — needs a Godot 4.7 binary)"
	echo
	echo "## Seed validation"
	echo "- ${SEED_STATUS}"
	echo "- \`${SEED_SUMMARY}\`"
	echo

	cat <<'PROSE'
## Launch flow

Title → Bid → Combat [boss fights back] → Verdict → New Run

## Working now

- Deterministic Moment-clock combat sim
- Per-part HP + conditions + bleed-out
- Enemy AI incl. the Incinedile phase machine
- Hype / tag / spectacle engines
- 6 real demo skills via SkillBook
- Playable HUD with live arena + tick rail + MOVE
- Bid & verdict screens
- Save / resume

## Known stubs / placeholder

- 37 of 43 skills fall back to a generic strike
- R14 numbers are placeholder
- Patron economy not wired
- Accessibility (a11y) pass pending
- Visuals are placeholder — "Rework Visuals Properly" epic

## Current blockers

- None critical
- KAN-2 sitting implementations — priming / shock / R14 numbers — pending
PROSE
} > "$OUT"

echo "Wrote ${OUT} (engine ${ENGINE}, ${TESTS} tests discovered, seed validation ${SEED_STATUS})."
